### PR TITLE
Test individual providers

### PR DESCRIPTION
**Pull request by robertoaloi**
This PR introduces some basic test for the individual providers. It also allows to specify the provider options via the application environment.

The latter partially solves the following problem: the `Options` argument in `aws_credentials_provider:fetch/1` is not exposed to the user via the `aws_credentials` api, making it hard to configure a backend (otherwise the user would need to invoke the `aws_credentials_provider` functions directly). Also, `Options` are typically used on bootstrap, so the user needs a way to pass the options along. This is, for example, shown in the tests for the `file` backend, where the default path to the credentials is overridden.

### CODE REVIEW

**Comment by mrallen1** [comment]
With respect to the tests themselves and their implementation I'm generally 👍 on that.

With respect to the API change to make the provider list of 2-tuples, I am 👎 on that. It was an oversight on my part _not_ to include a `get_credentials/1` function that takes options (as a proplist or map) in the `aws_credentials` module. I would prefer to do that and make `get_credentials/0` pass an empty map or empty proplist to `get_credentials/1`.

**Comment by robertoaloi** [comment]
Hi @mrallen1 , the problem with that approach (in the original version of this branch I simply added the tests, without applying any change to the API) is that it's too late to apply the options. `fetch_credentials/0` is initially called in the `init/1` during the `gen_server` bootstrap and later on on `refresh`. The `get_credentials/0` that you suggest to extend with an additional argument is only used to retrieve the credentials from the state. But we would not even reach that point since the server would have crashed on init (eg trying to fetch non existing credentials).

This is why I say that this PR "partially solves" the issue. The real solution is to restructure the whole thing so that the options are somehow passed to the bootstrap.

**Comment by robertoaloi** [comment]
@mrallen1 Any update?

**Comment by mrallen1** [comment]
@robertoaloi Yeah, I just got power/water/internet back here in Houston, so I was thinking I wanted to solve this "the right way" which means a refactor of start up as you point out. I'm planning to do that in the next day or two.

**Comment by robertoaloi** [comment]
@mrallen1 Sounds good, let me know if you need help. Given that this PR is backward compatible (the old configuration format is still possible), we could actually merge this and then work on the refactoring (once the tests are there). The alternative is to rebase these tests on top of your refactoring. Whatever you prefer.

**Review by jfacorro — APPROVED** [review]
I read the conversation in the PR and I think that since this a backward compatible change (as @robertoaloi points out) I would be ok with us merging this. The test suite is still valuable in the sense that more test cases could be added for the different providers, even after the refactoring is done.

**Comment by robertoaloi** [comment]
@mrallen1 Any updates? We can help out with the refactoring if you need :)

**Comment by robertoaloi** [comment]
Merging this mostly to get the tests in. I consider the initialization mechanism to still be discussed, possibly as an evolution of #20. For now, it does not makes sense to keep a `master` broken and without tests.

**Pull request merged**
